# Site settings
title: Concur Developer Portal
email: devx@concur.com
description: Concur docs provides comprehensive information on working with the Concur platform
baseurl: "" # the subpath of your site, /developer.concur.com
canonical_site: https://developer.concur.com
twitter_username: concurapi
github_username:  concur
repository_url: "https://github.com/concur/developer.concur.com/blob/preview/"
exclude:
  - build
  - shippable.yml
  - awscli-bundle.zip
  - awscli-bundle
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock

# Build settings
kramdown:
  input: GFM
